/**
 * @file model_provider.hpp
 * @brief Abstract interface and types for LLM model providers.
 */

#pragma once

#include <atomic>
#include <functional>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

#include <nlohmann/json.hpp>
#include "arn/core/confirmation/confirmation_request.hpp"
#include "arn/core/tool/tool_registry.hpp"

namespace arn::core {

/**
 * @brief Supported model provider backends.
 */
enum class ProviderType {
    none,       ///< No provider selected.
    deepseek,   ///< DeepSeek API backend.
    gemini,     ///< Google Gemini API backend.
    openrouter, ///< OpenRouter multi-model gateway backend.
    custom      ///< Custom or mock provider implementation.
};

/**
 * @brief Returns the human-readable display name for a provider type.
 * @param type Provider type enum value.
 * @return String view such as "Gemini", "DeepSeek", "OpenRouter".
 */
[[nodiscard]] inline std::string_view provider_type_name(ProviderType type) noexcept {
    switch (type) {
    case ProviderType::deepseek:
        return "DeepSeek";
    case ProviderType::gemini:
        return "Gemini";
    case ProviderType::openrouter:
        return "OpenRouter";
    case ProviderType::custom:
        return "Custom";
    case ProviderType::none:
        return "none";
    }
    return "unknown";
}

/**
 * @brief Parses a ProviderType enum from a string name.
 * @param name Provider identifier string (case-sensitive lowercase: "gemini", "deepseek", "openrouter", "custom").
 * @return Corresponding ProviderType or ProviderType::none if unrecognized.
 */
[[nodiscard]] inline ProviderType provider_type_from_name(std::string_view name) noexcept {
    if (name == "gemini")
        return ProviderType::gemini;
    if (name == "deepseek")
        return ProviderType::deepseek;
    if (name == "openrouter" || name == "open-router" || name == "open_router")
        return ProviderType::openrouter;
    if (name == "custom")
        return ProviderType::custom;
    return ProviderType::none;
}

/**
 * @brief Generalized result structure returned by high-level API calls (e.g. prompt, list_models).
 */
struct ApiResult {
    /// True if the operation succeeded; false otherwise.
    bool ok{false};
    /// Response text or error explanation message.
    std::string message;
    /// Optional list of model names (populated by list_models).
    std::vector<std::string> models;
    /// True if the operation was aborted due to cancellation.
    bool cancelled{false};
};

/// Callback receiving streaming incremental text tokens as they arrive from the model.
using TextStreamCallback = std::function<void(std::string_view text_delta)>;
/// Callback receiving status updates, retry notifications, and tool execution notices.
using ProgressCallback = std::function<void(std::string_view progress_message)>;

/**
 * @brief Grouping of streaming event callbacks.
 */
struct StreamCallbacks {
    /// Incremental token delivery callback.
    TextStreamCallback on_text;
    /// Status and progress notification callback.
    ProgressCallback on_progress;
};

/**
 * @brief Represents a tool invocation request emitted by the model.
 */
struct ToolCall {
    /// Provider-assigned call ID (used to match tool responses in continue_turn).
    std::string id;
    /// Name of the requested tool in ToolRegistry.
    std::string name;
    /// Structured argument payload provided by the model.
    nlohmann::json arguments;
};

/**
 * @brief Response from executing a tool, sent back to the model.
 */
struct ToolResponse {
    /// Matching call ID from the corresponding ToolCall.
    std::string call_id;
    /// Tool name.
    std::string name;
    /// Execution output JSON payload.
    nlohmann::json result;
};

/**
 * @brief Result of a single model interaction step (start_turn or continue_turn).
 */
struct ModelTurn {
    /// True if the turn request succeeded.
    bool ok{false};
    /// Text response generated by the model during this turn.
    std::string text;
    /// Tool calls requested by the model during this turn (empty if model finished).
    std::vector<ToolCall> tool_calls;
    /// Error message if ok is false.
    std::string error_message;
    /// True if the turn was cancelled by the user.
    bool cancelled{false};
};

/**
 * @brief Capabilities supported by a specific model or provider.
 */
struct ModelCapabilities {
    /// Whether the model supports function / tool calling.
    bool supports_tools{true};
    /// Whether the model supports token streaming.
    bool supports_streaming{true};
    /// Whether the model supports an explicit system instruction / developer prompt.
    bool supports_system_instruction{true};
};

/**
 * @brief Abstract interface for LLM backends.
 *
 * Implementations manage wire formats, authentication, SSE chunk decoding,
 * and multi-turn message history for specific providers.
 */
class IModelProvider {
public:
    virtual ~IModelProvider() = default;

    /// Returns the provider type enum.
    [[nodiscard]] virtual ProviderType type() const noexcept = 0;
    /// Returns the human-readable provider name.
    [[nodiscard]] virtual std::string_view name() const noexcept = 0;

    /**
     * @brief Picks the recommended default model from an available list.
     * @param models Vector of available model IDs.
     * @return Selected model identifier.
     */
    [[nodiscard]] virtual std::string
    preferred_model(const std::vector<std::string>& models) const = 0;

    /**
     * @brief Returns feature capabilities supported by the given model.
     * @param model Model identifier.
     * @return ModelCapabilities struct.
     */
    [[nodiscard]] virtual ModelCapabilities model_capabilities(std::string_view /*model*/) const {
        return ModelCapabilities{};
    }

    /**
     * @brief Queries the provider endpoint to list available models and validate credentials.
     * @param api_key API key / bearer token.
     * @param cancel_requested Optional cancellation token.
     * @return ApiResult containing the list of discovered model identifiers.
     */
    [[nodiscard]] virtual ApiResult list_models(const std::string& api_key,
                                                const std::atomic_bool* cancel_requested = nullptr) = 0;

    /**
     * @brief Initiates a new user turn with the model.
     * @param api_key API key.
     * @param model Selected model identifier.
     * @param system_instruction System instruction / persona.
     * @param user_prompt User input text.
     * @param tools Registry of tools available to the model.
     * @param callbacks Streaming and progress callbacks.
     * @param cancel_requested Optional cancellation token.
     * @return ModelTurn containing text and/or requested tool calls.
     */
    [[nodiscard]] virtual ModelTurn
    start_turn(const std::string& api_key, const std::string& model,
               const std::string& system_instruction, const std::string& user_prompt,
               const ToolRegistry& tools,
               const StreamCallbacks& callbacks = {},
               const std::atomic_bool* cancel_requested = nullptr) = 0;

    /**
     * @brief Continues an active multi-round turn by supplying tool execution results.
     * @param api_key API key.
     * @param model Selected model identifier.
     * @param system_instruction System instruction.
     * @param tool_responses Results of executing the tool calls requested in the previous turn.
     * @param tools Tool registry.
     * @param callbacks Streaming and progress callbacks.
     * @param cancel_requested Optional cancellation token.
     * @return ModelTurn containing subsequent text and/or additional tool calls.
     */
    [[nodiscard]] virtual ModelTurn
    continue_turn(const std::string& api_key, const std::string& model,
                  const std::string& system_instruction,
                  const std::vector<ToolResponse>& tool_responses,
                  const ToolRegistry& tools,
                  const StreamCallbacks& callbacks = {},
                  const std::atomic_bool* cancel_requested = nullptr) = 0;

    /**
     * @brief Trims internal conversation history to avoid exceeding context window limits.
     * @param max_entries Maximum number of conversation message entries to retain.
     */
    virtual void trim_history(std::size_t max_entries) = 0;

    /// Aborts any in-flight HTTP request on this provider immediately.
    virtual void cancel_active_request() = 0;

    /// Clears all conversation history and resets session state.
    virtual void reset_session() = 0;

    /// Returns the current number of message entries in the provider session.
    [[nodiscard]] virtual std::size_t session_entries() const noexcept = 0;

    /**
     * @brief High-level helper executing a full turn loop (prompt -> tools -> answer).
     * @note Applications typically call AgentSession::prompt instead of calling submit_prompt directly.
     */
    [[nodiscard]] virtual ApiResult
    submit_prompt(const std::string& api_key, const std::string& model,
                  const std::string& system_instruction, const std::string& user_prompt,
                  const ToolRegistry& tools, const ConfirmationFn& confirm,
                  const TextStreamCallback& on_text = {},
                  const std::atomic_bool* cancel_requested = nullptr,
                  const ProgressCallback& on_progress = {});

    /// Overload of submit_prompt taking StreamCallbacks.
    [[nodiscard]] virtual ApiResult
    submit_prompt(const std::string& api_key, const std::string& model,
                  const std::string& system_instruction, const std::string& user_prompt,
                  const ToolRegistry& tools, const ConfirmationFn& confirm,
                  const StreamCallbacks& callbacks,
                  const std::atomic_bool* cancel_requested = nullptr) {
        return submit_prompt(api_key, model, system_instruction, user_prompt, tools, confirm,
                             callbacks.on_text, cancel_requested, callbacks.on_progress);
    }

    /// Legacy compatibility accessor returning type().
    [[nodiscard]] ProviderType kind() const noexcept { return type(); }
};

/**
 * @brief Factory function creating standard built-in model providers.
 * @param type Provider type to instantiate (gemini, deepseek, or openrouter).
 * @return Unique pointer to the created IModelProvider, or nullptr for unsupported types.
 */
[[nodiscard]] std::unique_ptr<IModelProvider> create_provider(ProviderType type);

} // namespace arn::core
